[package]
name = "zkc_state_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24.1"
strum_macros = "0.24.1"
ff = "0.12"
halo2_proofs = { git = "https://github.com/junyu0312/halo2", branch = "gpu", default-features = true }
halo2aggregator-s = { git = "https://github.com/DelphinusLab/halo2aggregator-s.git", tag = "bisect-lookup-0.2.1" }
halo2ecc-s = { git = "https://github.com/lanbones/halo2ecc-s.git", branch = "bisect-lookup" }
num-bigint = { version = "0.4", features = ["rand"] }
poseidon = { git = "https://github.com/lanbones/poseidon" }
rand = "0.8"
ark-std = { version = "0.3.0", features = ["print-trace"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
clap = { version = "3.2.22", features = ["derive", "cargo"] }
subtle = "2.4"
lazy_static = "1.4.0"
hex = "0.4"
mongodb = { version = "2.5.0", default-features = false, features = ["async-std-runtime"] }
ripemd = "0.1.3"
futures = "0.3.28"
tonic = "0.9.2"
tonic-web = "0.9.2"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.11"
tracing-subscriber = "0.3.17"
tonic-reflection = "0.9.2"
thiserror = "1.0.43"
bincode = "1.3.3"
base64 = "0.21.2"

[build-dependencies]
tonic-build = "0.9.2"

[dev-dependencies]
tempfile = "3.6.0"
tokio-stream = "0.1.14"
tower = "0.4.13"
