services:
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - './data/mongodb:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-OlQtOieOzHMSfaEaEZrkd}

  envoy:
    build: ./server/envoy
    ports:
      - 9901:9901
      - 50000:50000

  auth:
    build:
      context: ./services/auth
      args:
        - GOPROXY=${GOPROXY}
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME:-root}:${MONGODB_PASSWORD:-OlQtOieOzHMSfaEaEZrkd}@mongodb:27017

  kvpair:
    build:
      context: .
      args:
        - CRATESIOMIRROR=${CRATESIOMIRROR}
    ports:
      - 50051:50051
    environment:
      - RUST_LOG=${RUST_LOG}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME:-root}:${MONGODB_PASSWORD:-OlQtOieOzHMSfaEaEZrkd}@mongodb:27017
      - KVPAIR_PORT=50051
      - KVPAIR_GRPC_SERVER_URL=http://localhost:50051
