services:
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - './data/mongodb:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-OlQtOieOzHMSfaEaEZrkd}

  gateway:
    ports:
      - 50000:8080
    command:
      - "/gateway"
      - "-endpoint"
      - "kvpair:50051"
    build:
      context: ./gateway
      args:
        # Set proxy for go (e.g. https://goproxy.cn)
        - GOPROXY
    environment:
      - GRPC_GO_LOG_SEVERITY_LEVEL=${GRPC_GO_LOG_SEVERITY_LEVEL:-INFO}

  kvpair:
    build:
      context: .
      args:
        # Use a crates.io mirror (e.g. sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/)
        - CRATESIOMIRROR
        # Set build profile (https://doc.rust-lang.org/cargo/reference/profiles.html) for cargo (e.g. dev)
        - CARGOPROFILE
    ports:
      - 50051:50051
    environment:
      - RUST_LOG=${RUST_LOG}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME:-root}:${MONGODB_PASSWORD:-OlQtOieOzHMSfaEaEZrkd}@mongodb:27017
      - KVPAIR_PORT=50051
      - KVPAIR_GRPC_SERVER_URL=http://localhost:50051
