services:
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017

  envoy:
    build: ./server/envoy
    ports:
      - 9901:9901
      - 50000:50000
  auth:
    build: ./services/auth

  kvpair:
    build:
      context: .
    ports:
      - 50051:50051
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
