on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v2
      # Install rust-toolchain from rust-toolchain file
      # See https://github.com/dtolnay/rust-toolchain/issues/77#issuecomment-1462824940
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xom9ikk/dotenv@v2
        with:
          mode: development
      - uses: arduino/setup-protoc@v2
      - uses: Swatinem/rust-cache@v2
      - uses: docker/setup-buildx-action@v2
      - name: build docker compose file
        uses: docker/bake-action@v3
        with:
          load: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max,compression=zstd
      - uses: isbang/compose-action@v1.5.0
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v2
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v2
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo clippy -- -D warnings
