on: [push, pull_request]

name: Build container images

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: "."
            name: "kvpair"
          - context: "./server/envoy"
            name: "envoy"
          - context: "./services/auth"
            name: "auth"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/zkc-stateservice:latest"
