on: [push, pull_request]

name: Check protobuf

env:
  PROTOC_VERSION: "23.4"

jobs:
  check:
    name: Check protobuf definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v2
        with:
          version: "${{ env.PROTOC_VERSION }}"
      - run: |
          set -xeuo pipefail
          ./scripts/update_protos.sh
          if ! git diff --exit-code; then
            echo "Protobuf files in a inconsistent state"
            echo "Install protoc from https://github.com/protocolbuffers/protobuf/releases/tag/v${{ env.PROTOC_VERSION }}"
            echo "And run ./scripts/update_protos.sh and commit updates to git repo"
            exit 1
          fi

