on: [push, pull_request]

name: Check protobuf

jobs:
  check:
    name: Check protobuf definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: |
          set -xeuo pipefail
          protoc_version="$(nix develop -c protoc --version | awk '{print $NF}')"
          nix develop -c ./scripts/update_protos.sh
          if ! git diff --exit-code; then
            echo "Protobuf files in a inconsistent state"
            echo "Install protoc from https://github.com/protocolbuffers/protobuf/releases/tag/v${protoc_version}"
            echo "And run ./scripts/update_protos.sh and commit updates to git repo"
            exit 1
          fi

